name: Deploy Renovate
on:
  workflow_dispatch:
  push:
    branches:
      - main
#       - dev
#   pull_request:
#     branches:
#       - dev
jobs:
  renovate:
    uses: JHOFER-Cloud/helm-ci/.github/workflows/k8s-deploy-template.yml@v3.1.2
    with:
      helm-ci_image_tag: 3.1.2
      app_name: renovate
      helm_repository: https://docs.renovatebot.com/helm-charts
      helm_chart: renovate
      helm_version: 39.200.1
      values_path: helm/values
      vault_url: https://vault.dev.k8.hla1.jhofer.lan
      vault_base_path: talos
      vault_kv_version: 2
      # vault_insecure_tls: true
      pr_deployments: false
    secrets:
      KUBE_CONFIG_LIVE: ${{ secrets.KUBE_CONFIG_LIVE }} ## HLA1 CONFIG
      KUBE_CONFIG_DEV: ${{ secrets.KUBE_CONFIG_DEV }} ## HLA1 CONFIG
      VAULT_TOKEN: ${{ secrets.HLA1_VAULT }}
